# version: '3.8'

services:

  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: user-db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped

  enquete-postgres:
    container_name: enquete-postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: enquete-db
    volumes:
      - enquete-postgres:/data/postgres
    ports:
      - 5434:5432
    networks:
      - spring-demo
    restart: unless-stopped

  reclamation-postgres:
    container_name: reclamation-postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: reclamation-db
    volumes:
      - reclamation-postgres:/data/postgres
    ports:
      - 5435:5432
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  enquete-postgres:
    driver: local
  reclamation-postgres:
    driver: local
  keycloak:
    driver: local
