version: '3.8'

services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      POSTGRES_DB: user-db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped

  enquete-postgres:
    container_name: enquete-postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      POSTGRES_DB: enquete-db
    volumes:
      - enquete-postgres:/data/postgres
    ports:
      - 5434:5432
    networks:
      - spring-demo
    restart: unless-stopped

  reclamation-postgres:
    container_name: reclamation-postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      POSTGRES_DB: reclamation-db
    volumes:
      - reclamation-postgres:/data/postgres
    ports:
      - 5435:5432
    networks:
      - spring-demo
    restart: unless-stopped

  metabase-postgres:
    container_name: metabase-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen
      POSTGRES_DB: metabase
    volumes:
      - metabase-postgres:/data/postgres
    ports:
      - 5436:5432
    networks:
      - spring-demo
    restart: unless-stopped

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: imen
      MB_DB_HOST: metabase-postgres
    depends_on:
      - metabase-postgres
    networks:
      - spring-demo
    restart: unless-stopped

  ia-service:
    build:
      context: ./microservice-ia
    container_name: ia-service
    ports:
      - "8000:8000"
    networks:
      - spring-demo
    restart: unless-stopped
    depends_on:
      - enquete-postgres

  rabbitmq:
    container_name: rabbitmq  # ✅ Ajoute ceci
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  enquete-postgres:
    driver: local
  reclamation-postgres:
    driver: local
  metabase-postgres:
    driver: local
