services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: imen                # Mot de passe changé ici
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: user-db                    # Nom base de données changé ici
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - spring-demo
    restart: unless-stopped

  keycloak:
    container_name: keycloak-bsn
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9092:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/user-db  # Keycloak connecté à la base user-db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: imen
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_RELATIVE_PATH: /auth
    networks:
      - spring-demo
    depends_on:
      - postgres
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local
