server:
  port: 8085

spring:
  application:
    name: enquete-service

  datasource:
    url: jdbc:postgresql://localhost:5434/enquete-db
    username: postgres
    password: imen
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      resourceserver:
        jwt:
         secret-key: GnzzsOitlN5w0CjaYODCk62v+/WmDl2HApnaRb/VEJg=
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  mail:
    host: smtp.gmail.com
    port: 587
    username: hadjyahyaimen@gmail.com
    password: ysip micw atgg ncvg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

file:
  uploads:
    photos-output-path: ./uploads

jwt:
  secret: GnzzsOitlN5w0CjaYODCk62v+/WmDl2HApnaRb/VEJg=
  expirationMs: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.authentication: DEBUG


feign:
  client:
    config:
      default:
        connectTimeout: 10000       # 10 secondes pour se connecter
        readTimeout: 120000         # ⬅️ 120 secondes pour attendre la réponse

