server:
  port: 8083

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: enquete-service
          uri: lb://enquete-service
          predicates:
            - Path=/enquete/**, /admin/enquetes/**


      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

jwt:
  secret: GnzzsOitlN5w0CjaYODCk62v+/WmDl2HApnaRb/VEJg=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.authentication: DEBUG
