server:
  port: 8083

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: enquete-service
          uri: lb://enquete-service
          predicates:
            - Path=/enquete/**, /admin/enquetes/**



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.web: DEBUG
    reactor.netty: DEBUG