server:
  port: 8083

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/hello

  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: info
  endpoint:
    info:
      enabled: true
  info:
    app:
      name: My Gateway Service
      description: API Gateway for Microservices Architecture
      version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
