server:
  port: 8086

spring:
  application:
    name: reclamation-service

  datasource:
    url: jdbc:postgresql://localhost:5435/reclamation-db
    username: postgres
    password: imen
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
firebase:
  server:
    key: AIzaSyBh4V_XCI2xKHrAc6StBioocz0BkOIT-Fs
